#!/bin/sh

# Clean up the files (the client and Java) installed into /usr/share/xmage
set -e

case "$1" in
  purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    if [ -d /usr/share/xmage ]; then
        rm -rf /usr/share/xmage
    fi
;;

*)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
;;
esac
